### PR TITLE
feat(StatusIcon) Add UnknownIcon to StatusIcon

### PR DESCRIPTION
**Pull request by gildub**
Adds an info status
Also resolves https://github.com/konveyor/lib-ui/issues/24
Helps with https://github.com/konveyor/virt-ui/issues/238

### CODE REVIEW

**Review by vconzola — CHANGES_REQUESTED** [review]
@gildub The color for the Unknown icon should be: #6A6E73
--pf-global--Color--200

**Comment by mturley** [comment]
@gildub also, all our icons for this component should be filled-in and not the outline variants. The warning icon is also wrong, which we have an issue for: https://github.com/konveyor/lib-ui/issues/24 (maybe we can just address both in this PR if you want)

**Comment by mturley** [comment]
@gildub I think we want to use the `global_Color_dark_200` instead of `global_warning_color_200`. Vince was describing a dark gray.

**Comment by gildub** [comment]
@mturley, no worries. I've changed it.

**Review by mturley — APPROVED** [review]
Sorry for my delay in reviewing this. LGTM.

**Comment by mturley** [comment]
Pushed `190830b` to force release because of the missing colon after `feat()`. ugh. need to loosen that config.

**Pull request merged**
